"""Utility functions and constants for weather and clothing analysis."""

CANDIDATE_LABELS = [
    "Rain",
    "Cold",
    "Hot",
    "Windy",
    "Freezing",
    "Warm",
    "Sunny",
    "Snow",
    "Stormy",
    "Mild",
    "Cool",
]

INCOMPATIBLE_KEYWORDS = {
    "Freezing": [
        "short sleeve",
        "short-sleeve",
        "sleeveless",
        "tank top",
        "crop top",
        "camisole",
        "tube top",
        "halter",
        "bandeau",
        "t-shirt",
        "tee",
        "polo",
        "blouse",
        "tunic",
        "vest",
        "shirt",
        "bodysuit",
        "corset",
        "bralette",
        "top",
        "off-shoulder",
        "cold shoulder",
        "spaghetti strap",
        "strapless",
        "racerback",
        "muscle shirt",
        "singlet",
        "peplum top",
        "wrap top",
        "bardot top",
        "shorts",
        "bermuda",
        "capris",
        "skort",
        "mini skirt",
        "skirt",
        "culottes",
        "hot pants",
        "board shorts",
        "cycling shorts",
        "gym shorts",
        "cargo shorts",
        "denim shorts",
        "chino shorts",
        "skater skirt",
        "pencil skirt",
        "dress",
        "sundress",
        "maxi dress",
        "midi dress",
        "mini dress",
        "gown",
        "cocktail",
        "slip dress",
        "romper",
        "jumpsuit",
        "playsuit",
        "maxi sundress",
        "summer dress",
        "beach dress",
        "wrap dress",
        "shirt dress",
        "tea dress",
        "bodycon dress",
        "skater dress",
        "pinafore",
        "shift dress",
        "sandal",
        "flip-flop",
        "slide",
        "mule",
        "clog",
        "slipper",
        "open toe",
        "peep toe",
        "pump",
        "heel",
        "flat",
        "loafer",
        "espadrille",
        "canvas",
        "sneaker",
        "trainer",
        "plimsoll",
        "gladiator sandal",
        "wedge",
        "slingback",
        "court shoe",
        "kitten heel",
        "stiletto",
        "ballerina",
        "ballet flat",
        "moccasin",
        "boat shoe",
        "swimsuit",
        "bikini",
        "monokini",
        "trunk",
        "board short",
        "rash guard",
        "sarong",
        "kaftan",
        "cover-up",
        "swim shorts",
        "beachwear",
        "swimwear",
        "bathing suit",
        "pareo",
        "kimono",
        "linen",
        "chiffon",
        "satin",
        "silk",
        "lace",
        "cotton",
        "sheer",
        "mesh",
        "organza",
        "tulle",
        "georgette",
        "viscose",
        "rayon",
        "crepe",
        "seersucker",
        "poplin",
        "voile",
        "eyelet",
        "broderie",
        "crochet",
        "jersey",
        "modal",
        "lyocell",
        "bamboo",
        "hemp",
        "muslin",
        "gauze",
    ],
    "Cold": [
        "short sleeve",
        "short-sleeve",
        "sleeveless",
        "tank top",
        "crop top",
        "camisole",
        "tube top",
        "halter",
        "bandeau",
        "t-shirt",
        "tee",
        "blouse",
        "bodysuit",
        "corset",
        "top",
        "strapless",
        "spaghetti strap",
        "off-shoulder",
        "muscle tee",
        "shorts",
        "bermuda",
        "hot pants",
        "mini skirt",
        "skort",
        "short shorts",
        "cycling shorts",
        "running shorts",
        "sundress",
        "maxi sundress",
        "slip dress",
        "summer dress",
        "beach dress",
        "mini dress",
        "strapless dress",
        "boho dress",
        "sandal",
        "flip-flop",
        "slide",
        "mule",
        "open toe",
        "peep toe",
        "espadrille",
        "slipper",
        "gladiator",
        "thong sandal",
        "pool slide",
        "swimsuit",
        "bikini",
        "monokini",
        "sarong",
        "cover-up",
        "swimwear",
        "bathing suit",
        "linen",
        "chiffon",
        "sheer",
        "mesh",
        "lace",
        "organza",
        "seersucker",
        "tulle",
        "net",
        "crochet",
    ],
    "Snow": [
        "sandal",
        "flip-flop",
        "slide",
        "mule",
        "open toe",
        "peep toe",
        "heel",
        "pump",
        "stiletto",
        "wedge",
        "flat",
        "ballerina",
        "loafer",
        "moccasin",
        "boat shoe",
        "espadrille",
        "canvas",
        "sneaker",
        "trainer",
        "plimsoll",
        "running shoe",
        "converse",
        "vans",
        "tennis shoe",
        "skate shoe",
        "slipper",
        "loafer",
        "oxford",
        "derby",
        "brogue",
        "monk strap",
        "shorts",
        "bermuda",
        "skort",
        "mini skirt",
        "hot pants",
        "skirt",
        "culottes",
        "capri",
        "cropped trouser",
        "sleeveless",
        "tank top",
        "crop top",
        "camisole",
        "tube top",
        "halter",
        "bandeau",
        "short sleeve",
        "t-shirt",
        "blouse",
        "mesh top",
        "sheer top",
        "lace top",
        "sundress",
        "slip dress",
        "dress",
        "maxi dress",
        "mini dress",
        "summer dress",
        "swimsuit",
        "bikini",
        "monokini",
        "swim trunks",
    ],
    "Rain": [
        "suede",
        "nubuck",
        "velvet",
        "silk",
        "satin",
        "canvas",
        "mesh",
        "white",
        "cream",
        "ivory",
        "light color",
        "light colour",
        "felt",
        "wool (untreated)",
        "cashmere",
        "knitted",
        "crochet",
        "sandal",
        "flip-flop",
        "slide",
        "mule",
        "open toe",
        "espadrille",
        "slipper",
        "canvas shoe",
        "fabric shoe",
        "suede shoe",
        "suede boot",
        "ugg",
        "sheepskin boot",
    ],
    "Hot": [
        "coat",
        "jacket",
        "parka",
        "puffer",
        "down",
        "trench",
        "raincoat",
        "blazer",
        "cardigan",
        "poncho",
        "cape",
        "cloak",
        "overcoat",
        "peacoat",
        "duffle coat",
        "bomber jacket",
        "leather jacket",
        "denim jacket",
        "windbreaker",
        "anorak",
        "gilet",
        "vest (padded)",
        "sweater",
        "jumper",
        "pullover",
        "turtleneck",
        "hoodie",
        "sweatshirt",
        "fleece",
        "knit",
        "thermal",
        "flannel",
        "heavy cotton",
        "thick shirt",
        "cable knit",
        "chunky knit",
        "scarf",
        "beanie",
        "glove",
        "mitten",
        "earmuff",
        "leg warmer",
        "thick sock",
        "tights",
        "pantyhose",
        "boot",
        "bootie",
        "uggs",
        "wellington",
        "galoshes",
        "knee high boot",
        "thigh high boot",
        "combat boot",
        "chelsea boot",
        "hiking boot",
        "snow boot",
        "winter boot",
        "wool",
        "cashmere",
        "fur",
        "faux fur",
        "shearling",
        "leather",
        "suede",
        "corduroy",
        "velvet",
        "fleece",
        "down",
        "synthetic insulation",
        "tweed",
        "herringbone",
        "flannel",
        "boucle",
        "chenille",
        "angora",
        "mohair",
        "alpaca",
        "neoprene",
    ],
    "Warm": [
        "winter coat",
        "heavy coat",
        "parka",
        "puffer",
        "down jacket",
        "fur coat",
        "shearling",
        "ski suit",
        "snow suit",
        "thick coat",
        "heavy jacket",
        "wool coat",
        "sweater",
        "jumper",
        "pullover",
        "hoodie",
        "sweatshirt",
        "fleece",
        "turtleneck",
        "thermal",
        "flannel",
        "thick scarf",
        "heavy gloves",
        "mittens",
        "earmuffs",
        "beanie",
        "fur hat",
        "ushanka",
        "snow boot",
        "winter boot",
        "uggs",
        "moon boot",
        "insulated boot",
        "heavy wool",
        "thick knit",
        "fur",
        "down",
        "shearling",
        "quilted",
    ],
    "Cool": [
        "swimsuit",
        "bikini",
        "monokini",
        "sarong",
        "cover-up",
        "swim trunks",
        "board shorts",
        "sundress",
        "maxi sundress",
        "summer dress",
        "slip dress",
        "beach dress",
        "mini dress",
        "strapless",
        "flip-flop",
        "slide",
        "thong sandal",
        "sheer",
        "mesh",
        "see-through",
        "fishnet",
        "tube top",
        "bandeau",
        "micro mini skirt",
        "linen pants",
    ],
    "Mild": [
        "swimsuit",
        "bikini",
        "monokini",
        "snow boot",
        "ski suit",
        "heavy parka",
        "arctic coat",
    ],
    "Stormy": [
        "sundress",
        "maxi dress",
        "mini dress",
        "slip dress",
        "summer dress",
        "beach dress",
        "wrap dress",
        "tea dress",
        "skater dress",
        "short sleeve",
        "short-sleeve",
        "sleeveless",
        "tank top",
        "crop top",
        "tube top",
        "halter",
        "bandeau",
        "camisole",
        "strapless",
        "shorts",
        "mini skirt",
        "skirt",
        "sandal",
        "flip-flop",
        "slide",
        "mule",
        "open toe",
        "peep toe",
        "espadrille",
        "canvas",
        "flat",
        "heel",
        "pump",
        "swimsuit",
        "bikini",
        "monokini",
        "sarong",
        "cover-up",
        "linen",
        "chiffon",
        "silk",
        "lace",
        "sheer",
        "mesh",
        "organza",
    ],
}


def get_temperature_label(temp: float) -> str:
    """Converts a numerical temperature into a descriptive weather label.

    Args:
        temp (float): The temperature in Celsius.

    Returns:
        str: A descriptive string (e.g., "Freezing", "Cold", "Hot").
    """
    rules = [
        (0, "Freezing"),
        (5, "Cold"),
        (10, "Chilly"),
        (15, "Cool"),
        (28, "Warm"),
        (float("inf"), "Hot"),
    ]
    for limit, label in rules:
        if temp < limit:
            return label
    return "Hot"


def get_humidity_label(humidity: int) -> str:
    """Converts a numerical humidity percentage into a descriptive label.

    Args:
        humidity (int): The relative humidity percentage.

    Returns:
        str: A descriptive string (e.g., "Dry", "Comfortable", "Humid").
    """
    rules = [(30, "Dry"), (60, "Comfortable"), (float("inf"), "Humid")]
    for limit, label in rules:
        if humidity < limit:
            return label
    return "Humid"


def get_wind_label(speed: float) -> str:
    """Converts a numerical wind speed into a descriptive label.

    Args:
        speed (float): The wind speed in meters per second.

    Returns:
        str: A descriptive string (e.g., "Calm", "Storm").
    """
    rules = [
        (1, "Calm"),
        (4, "Light Breeze"),
        (8, "Gentle Breeze"),
        (13, "Moderate Breeze"),
        (19, "Fresh Breeze"),
        (25, "Strong Breeze"),
        (33, "Storm"),
        (float("inf"), "Hurricane"),
    ]
    for limit, label in rules:
        if speed < limit:
            return label
    return "Hurricane"